//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchLog
    {
        public int id { get; set; }
        public string searchTerm { get; set; }
        public string searchPath { get; set; }
        public string resultFilePath { get; set; }
        public Nullable<System.DateTime> DateSearched { get; set; }
        public string SearchType { get; set; }
    }
}
